#!/bin/bash
################################################################################
#: Title       : Exercise 2: max3
#: Date        : 2017-Dec-5
#: Author      : Anthony Tilelli (modified version)
#: Version     : 1
#: Description : sorts 3 integers from largest to smallest
#: Options     : NONE
################################################################################
max3() #original
{
  declare -n _max3=${4:-_MAX3}
  (( $# < 3 )) && return 4
  (( $1 > $2 )) && set -- "$2" "$1" "$3"
  (( $2 > $3 )) && set -- "$1" "$3" "$2"
  (( $1 > $2 )) && set -- "$2" "$1" "$3"
  _max3=( "$3" "$2" "$1" )
}

max3_modified() #original
{

  #check if $4 is a valid variable name and currently inset
  remove_="${1//_/}"
  case "$remove_" in
    *[[:blank:]]*) return 1;;
    *[[:punct:]]*) return 2 ;;
  esac

  declare -n _max3=${4:-_MAX3}
  (( $# < 3 )) && return 4
  (( $1 > $2 )) && set -- "$2" "$1" "$3"
  (( $2 > $3 )) && set -- "$1" "$3" "$2"
  (( $1 > $2 )) && set -- "$2" "$1" "$3"
  _max3=( "$3" "$2" "$1" )
}
max3_modified 1 2 3
echo "Sorted: ${_MAX3[@]}"